Stratified K-Fold Cross Validation
SeanLF/CSI4900 pull request #30
Opened 2016-11-30 23:15 UTC by SeanLF

2016-11-30 23:19 UTC, SeanLF commented on active_learning/learn.py
> +        print('Cross val iteration done\n')
To remove

2016-12-01 17:58 UTC, markkasun requested changes

2016-12-01 17:58 UTC, markkasun commented on active_learning/learn.py
> +    # active learning
Try to reuse the code from learning.py. Create a separate method with condition statements that determine whether to produce intermediate results

2016-12-01 17:58 UTC, markkasun commented on active_learning/learn.py
> +    skf.get_n_splits(X, y)
Remove this line. Does nothing.

2016-12-01 17:58 UTC, markkasun commented on active_learning/learn.py
> +    dataset_name = 'Four University'
Should be a parameter to be able to run on other datasets. Same with other variables below.

2016-12-02 01:13 UTC, markkasun commented on active_learning/learn.py
> +    labeled_instances = kwargs.pop('dataset_id', 5)
5?

2016-12-02 01:13 UTC, markkasun commented on active_learning/learning.py
> +        train_dataset, train_dataset_labeled, test_dataset, lookup_train, lookup_test, self.lookup_table = self.setup_datasets(X, self.y, self.lookup_table, train_size)
Don't like the split lines? Much easier to read imo.

2016-12-02 01:13 UTC, markkasun commented on active_learning/custom_labelers.py
> +    def __init__(self, **kwargs):
Should make oracle_dataset a mandatory field?
     if self.oracle_dataset is None:
            raise TypeError(
                "__init__() missing required keyword-only argument: 'oracle_dataset'"
            )

2016-12-02 01:20 UTC, SeanLF commented on active_learning/learn.py
> +    labeled_instances = kwargs.pop('dataset_id', 5)
oh yeah, my bad

2016-12-02 01:20 UTC, SeanLF commented on active_learning/learning.py
> +        train_dataset, train_dataset_labeled, test_dataset, lookup_train, lookup_test, self.lookup_table = self.setup_datasets(X, self.y, self.lookup_table, train_size)
nope, python multiline statements are gross 😛

2016-12-02 01:21 UTC, SeanLF commented on active_learning/custom_labelers.py
> +    def __init__(self, **kwargs):
might have to move my params around

2016-12-02 01:24 UTC, markkasun commented on active_learning/learning.py
> +        train_dataset, train_dataset_labeled, test_dataset, lookup_train, lookup_test, self.lookup_table = self.setup_datasets(X, self.y, self.lookup_table, train_size)
But think of the PEP8!

2016-12-02 01:31 UTC, SeanLF commented on active_learning/learning.py
> +        train_dataset, train_dataset_labeled, test_dataset, lookup_train, lookup_test, self.lookup_table = self.setup_datasets(X, self.y, self.lookup_table, train_size)
i increased the max line length haha

2016-12-02 15:55 UTC, markkasun approved these changes

2016-12-02 15:56 UTC, merged